### ISSUE TITLE
Can't figure out required permissions for pipeline to deploy function app

### ISSUE THREAD

**Issue by thomaseyde** [Cheranga/Demo.Bicep.Azure.Functions#2]
Hi,

I read your article [Azure Bicep and Azure DevOps to deploy a function app](https://medium.com/cheranga/azure-bicep-and-azure-devops-to-deploy-a-function-app-a707c13b2bff) with great interest as I am currently trying to set up something similar.

Nice touch on how to setup key vault access, btw.

My problem is the pipeline fails to deploy the function app resource with an error `Conflict` `error` `DeploymentActive` `Unable to edit or replace deployment '...': previous deployment from '...' is still active (expiration time is '...').`

When I redeploy from the DevOps portal, it continues smoothly.

I suspect missing permissions on the pipeline itself, but I can't figure out what they are.

**Comment by thomaseyde** [comment]
Typical pebkac. I named two modules the same. Once I removed the duplicate name, everything worked.

**Comment by Cheranga** [comment]
Hi Thomas.
I was going to reply to you today evening. Sorry to send this message late.

Happy that you figured it out. My initial thoughts were that it could have
been a service principal issue.

Thanks for the feedback mate, please let me know if you have any feedback.

Cheers,
Cheranga
